### ISSUE TITLE
404是不是网站改了

### ISSUE THREAD

**Issue by fangxuanhao** [gongice/easy_university_selection#3]
'http://gkcx.eol.cn/schoolhtm/scores/provinceScores31_10016_10035_10036.xml'

Traceback (most recent call last):
  File "C:/Users/Administrator.DESKTOP-DHPJ48Q/Desktop/easy_university_selection-master/aaa.py", line 10, in <module>
    response = urllib2.urlopen(req)
  File "D:\Python27\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python27\Lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "D:\Python27\Lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python27\Lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "D:\Python27\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\Lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\Python27\Lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "D:\Python27\Lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python27\Lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "D:\Python27\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\Lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by siu91** [comment]
网站改版了，抓取方式不适用了

**Comment by xizhesun** [comment]
请问开发者有办法修正抓取方式吗

**Comment by siu91** [comment]
> 请问开发者有办法修正抓取方式吗

暂时没有精力投入
